spring:
  application:
    name: biblioteca
  security:
    user:
      name: admin
      password: minuevaClave#26875


function:
  azure:
    url:
      base:  https://func-biblioteca-djfmfvaacbfvdcfe.eastus2-01.azurewebsites.net/api/
server:
  port: 8080

#logging:
#  level:
#    root: DEBUG
